### PR TITLE
Adding new inputs (password, email, number)

### PR DESCRIPTION
**Pull request by marciovicente**

### CODE REVIEW

**Comment by rafaelverger** [comment]
what about `[type="date"]` ?

**Comment by marciovicente** [comment]
Done @rafaelverger

**Comment by rafaelverger** [comment]
nice... what do you think about adding those inputs to `demo.html`?

**Comment by marciovicente** [comment]
All inputs are equals @rafaelverger

Em ter, 24 de mar de 2015 às 15:32, Rafael Nunes Verger <
notifications@github.com> escreveu:

**Comment by rafaelverger** [comment]
They are not equals, @marciovicente ... they are rendered differently if the browser supports those types!

**Comment by marciovicente** [comment]
I think that only in Chrome, date input has arrow to open datepicker,
otherwise they're equals.

Em ter, 24 de mar de 2015 às 16:04, Rafael Nunes Verger <
notifications@github.com> escreveu:

**Comment by shankarcabus** [comment]
No, @marciovicente They are differents. Some inputs has arrows, like the `select` and this may be a problem. I agree to put those elements in the demo page.

**Comment by marciovicente** [comment]
Updated @shankarcabus @rafaelverger

**Comment by marciovicente** [comment]
I'm waiting.. @shankarcabus @rafaelverger @andersonba

**Comment by andersonba** [comment]
LGTM

**Pull request merged**
