### PR TITLE
Improve button with icons

### PR DESCRIPTION
**Pull request by marciovicente**
**Before**
image

**After**
image

### CODE REVIEW

**Comment by rafaelverger** [comment]
LGTM

**Comment by rafaelverger** [comment]
LGTM

**Comment by andersonba** [comment]
Add the modifier in the button's comments (the "documentation") :smile: 
https://github.com/jusbrasil/monalisa/blob/master/scss/components/_buttons.scss#L25

**Comment by marciovicente** [comment]
@andersonba  :+1:

**Comment by neliocastro** [comment]
E se o icone for a Direita?

**Comment by marciovicente** [comment]
@neliocastro 

image

**Comment by andersonba** [comment]
LGTM

**Comment by rafaelverger** [comment]
@neliocastro the communication over here must be in english only

**Pull request merged**
