### PR TITLE
Using relative unit to set switch's dimension

### PR DESCRIPTION
**Pull request by rafaelverger**
image

### CODE REVIEW

**Comment by rafaelverger** [comment]
@marciovicente @andersonba

**Comment by andersonba** [comment]
Good demo :+1: 
Did you tested breaking the label text in two lines?
BMC, LGTM

**Comment by rafaelverger** [comment]
Now it works :)
image

**Comment by marciovicente** [comment]
LGTM! Go ahead! Pls!

**Comment by andersonba** [comment]
GGG = Go go go

**Pull request merged**
